### ISSUE TITLE
Aquarius 0.3.8 spits errors until Elasticsearch is fully up

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/barge#180]
## Environment
`Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

## Trying to start local testnet with Aquarius 0.3.8
```
# Clear docker;
docker rm $(docker ps -a -q) 
system prune -a

# Set versions;
export AQUARIUS_VERSION=v0.3.8
export KEEPER_VERSION=v0.10.3

# Start barge (clean pull from Master)
. ./start_ocean.sh
```

Fails with; 

```
aquarius_1                   | 2019-08-26 13:25:41 2d7d014d075c elasticsearch[64] WARNING HEAD http://elasticsearch:9200/ [status:N/A request:0.007s]
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
aquarius_1                   |     (self._dns_host, self.port), self.timeout, **extra_kw)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
aquarius_1                   |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
aquarius_1                   |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
aquarius_1                   |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
aquarius_1                   | socket.gaierror: [Errno -2] Name does not resolve
aquarius_1                   | 
aquarius_1                   | During handling of the above exception, another exception occurred:
aquarius_1                   | 
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
aquarius_1                   |     method, url, body, retries=Retry(False), headers=request_headers, **kw
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
aquarius_1                   |     _stacktrace=sys.exc_info()[2])
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 344, in increment
aquarius_1                   |     raise six.reraise(type(error), error, _stacktrace)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
aquarius_1                   |     raise value
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
aquarius_1                   |     chunked=chunked)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
aquarius_1                   |     conn.request(method, url, **httplib_request_kw)
aquarius_1                   |   File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
aquarius_1                   |     self._send_request(method, url, body, headers, encode_chunked)
aquarius_1                   |   File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
aquarius_1                   |     self.endheaders(body, encode_chunked=encode_chunked)
aquarius_1                   |   File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
aquarius_1                   |     self._send_output(message_body, encode_chunked=encode_chunked)
aquarius_1                   |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
aquarius_1                   |     self.send(msg)
aquarius_1                   |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
aquarius_1                   |     self.connect()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 183, in connect
aquarius_1                   |     conn = self._new_conn()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
aquarius_1                   |     self, "Failed to establish a new connection: %s" % e)
aquarius_1                   | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection>
```

Starting with Mongo seems to be ok;
`. ./start_ocean.sh --local-spree-node --no-pleuston --no-brizo --mongodb `

## Starting with default versions (latest);
Ran into the memory limit for elastic, fixed by increasing resources required by elastic container;

``` 
sudo vi /etc/sysctl.conf
# Add the following; vm.max_map_count=262144
```

Restart to apply the config; `sudo sysctl -p`

**Comment by H34D** [comment]
i can confirm having:

```
aquarius_1                   | 2019-08-26 13:25:41 2d7d014d075c elasticsearch[64] WARNING HEAD http://elasticsearch:9200/ [status:N/A request:0.007s]
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
aquarius_1                   |     (self._dns_host, self.port), self.timeout, **extra_kw)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
aquarius_1                   |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
aquarius_1                   |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
aquarius_1                   |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
aquarius_1                   | socket.gaierror: [Errno -2] Name does not resolve
```

on mac too, once elastic is running and i restart the container it works. Seems we need to have to wait in Aquarius till elastic is setup properly.

**Comment by MarcusJones** [comment]
Still facing this issue. Aqua does start with v0.3.8. Failed to start with v0.3.9.
