### ISSUE TITLE
address.json doesn't have "development" entries. Error deploying contracts?

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#292]
**Describe the bug**

Core problem: The `address.json` file - which Barge is supposed to update - doesn't have a `"development"` entry. And, that may be because in deploying FixedRateExchange it hits an error ('invalid address or ENS name'). Details below.

It's a critical bug, since anyone who has it can't use anything that depends on Barge. Incl market, ocean.js, ocean.py. It's blocking me in df-py (Data Farming) work.

**To reproduce**

Basically, grab a fresh barge and try to do anything with it. For example:

```console
# 1. Grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

# 2. Clean up old containers (to be sure)
docker system prune -a --volumes

# 3. Run barge
./start_ocean.sh --with-c2d
```

Many things come up as expected. But several issues emerge. Here are some:

Issue: In the barge log:
```text
aquarius_1         | Traceback (most recent call last):
aquarius_1         |   File "events-monitor-main.py", line 52, in <module>
aquarius_1         |     run_events_monitor()
aquarius_1         |   File "events-monitor-main.py", line 38, in run_events_monitor
aquarius_1         |     monitor = EventsMonitor(setup_web3(config_file, logger), config_file)
aquarius_1         |   File "/aquarius/aquarius/events/events_monitor.py", line 69, in __init__
aquarius_1         |     self._start_block = get_metadata_start_block()
aquarius_1         |   File "/aquarius/aquarius/events/util.py", line 169, in get_metadata_start_block
aquarius_1         |     if "startBlock" in address_json[network]
aquarius_1         | KeyError: 'development'
```

Issue: Found via ocean.py's [simple README](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/data-nfts-and-datatokens-flow.md) until the line `ocean.create_erc721_nft('NFTToken1', 'NFT1', alice_wallet)`. Traceback:

```console
>>> ocean.create_erc721_nft('NFTToken1', 'NFT1', alice_wallet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 164, in create_erc721_nft
    nft_factory = self.get_nft_factory()
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/ocean.py", line 209, in get_nft_factory
    nft_factory_address = get_address_of_type(
  File "/home/trentmc/code/ocean.py/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/ocean.py/ocean_lib/ocean/util.py", line 81, in get_address_of_type
    if address_type not in addresses.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

Issue: [`address.json`](https://github.com/oceanprotocol/barge/files/8777545/address.json.txt) file doesn't have a `"development"` entry. Example: 
```console
>>> cat /home/trentmc/.ocean/ocean-contracts/artifacts/address.json
{
  "rinkeby": {
    "chainId": 4,
...
<<and no "development" entry>>
}
```

----
Update: I ran barge again, now sending stdout and stderr logs to [out.txt](https://github.com/oceanprotocol/barge/files/8777613/out.txt).

And, here's another version with a bunch of annoying escape characters removed: 
[out2.txt](https://github.com/oceanprotocol/barge/files/8777672/out2.txt)

----
Update: I found the following in the log file too. It hit an error deploying `FixedRateExchange`. Perhaps because it hit that error, nothing else got deployed? Perhaps something got changed in the contracts that caused the error?
```text
ocean-contracts_1  | 	npx hardhat verify --network development --constructor-args args1.js 0x8930D1F61Defb9CBD652136B4C3D93f19AC35678
ocean-contracts_1  | Deploying FixedrateExchange
ocean-contracts_1  | Error: invalid address or ENS name (argument="name", value={"gasLimit":8000000}, code=INVALID_ARGUMENT, version=contracts/5.6.0)
ocean-contracts_1  |     at Logger.makeError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:233:21)
ocean-contracts_1  |     at Logger.throwError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:242:20)
ocean-contracts_1  |     at Logger.throwArgumentError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:245:21)
ocean-contracts_1  |     at /ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:94:32
ocean-contracts_1  |     at step (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:48:23)
ocean-contracts_1  |     at Object.next (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:29:53)
ocean-contracts_1  |     at fulfilled (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:20:58) {
ocean-contracts_1  |   reason: 'invalid address or ENS name',
ocean-contracts_1  |   code: 'INVALID_ARGUMENT',
ocean-contracts_1  |   argument: 'name',
ocean-contracts_1  |   value: { gasLimit: 8000000 }
ocean-contracts_1  | }
```

**Comment by trentmc** [comment]
I've been doing some of my own testing of this within df-py:
- Issue: [df-py#89](https://github.com/oceanprotocol/df-py/issues/89): Update to latest oceanprotocol contracts
- With [this PR](https://github.com/oceanprotocol/df-py/pull/90)
- I copied over the latest contracts into df-py.
- Everything compiles fine
- And, I can successfully deploy contracts to ganache via brownie & see the results. [Code](https://github.com/oceanprotocol/df-py/pull/90/files#diff-a6fbf02ecaa6eb99652a602805a983660b136019287106c99be2f3dd02054dee)

I did notice: as of recently, ERC721Factory constructor takes one less argument than it used to. Perhaps barge deployment of that contract wasn't updated?

**Comment by trentmc** [comment]
The main issue was that I was impatient, lol. It took longer than usual to get _everything_ in barge going, on the order of 10 min. But if I wait, then I don't have issues, yay:)

This slowness is new, as of V4, it was the "kindcluster" stuff. (Ref Marian)

So be it!

The good news is, it's solved:)
