### ISSUE TITLE
Barge failing: address.json is missing the entry for 'development' network

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#386]
## How to reproduce

I'm running MacOS.

**First, I did all the steps in pdr-backend [barge.md](https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/barge.md#install-barge)'s install section:**

That is: In barge console:
```console
# Grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

# Switch to predictoor branch of barge repo
git checkout predictoor

# Clean up previous Ocean-related dirs & containers (optional but recommended) 
rm -rf ~/.ocean
./cleanup.sh
docker system prune -a --volumes
```

And, I started Docker. (Needed for MacOS.)

**Then, I did the steps from predictoor local/local setup:**

(Including the fix from [#241](https://github.com/oceanprotocol/pdr-backend/issues/241) to remove `--no-aquarius --no-elasticsearch`.)

That is: In a different console:
```console
# set ganache block time to 5 seconds, try increasing this value if barge is lagging
export GANACHE_BLOCKTIME=5

#run barge with all bots except predictoor
./start_ocean.sh --no-provider --no-dashboard --predictoor --with-thegraph --with-pdr-trueval --with-pdr-trader --with-pdr-publisher --with-pdr-dfbuyer
```

**Here are my results:**

- The log showed that it was able to publish contracts
- I confirmed that by following directions in subgraph.md: going to the browser, opening subgraph page, and pasting in the query. [Here's the url](http://localhost:9000/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%7B%0A++predictContracts%7B%0A++++id%0A++++token%7B%0A++++++name%0A++++%7D%0A++++subscriptions%28orderBy%3A+expireTime+orderDirection%3Adesc+first%3A10%29%7B%0A++++++user+%7B%0A++++++++id%0A++++++%7D%0A++++++expireTime%0A++++%7D%0A++++slots%28orderBy%3A+slot+orderDirection%3Adesc+first%3A10%29%7B%0A++++++slot%0A++++++roundSumStakesUp%0A++++++roundSumStakes%0A++++++predictions%28orderBy%3A+timestamp+orderDirection%3Adesc%29%7B%0A++++++++stake%0A++++++++user+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++timestamp%0A++++++++payout%7B%0A++++++++++payout%0A++++++++++predictedValue%0A++++++++++trueValue%0A++++++++%7D%0A++++++%7D%0A++++++trueValues%7B%0A++++++++trueValue%0A++++++%7D%0A++++%7D%0A++%7D+%0A%7D). It successfully output all the feeds.
- BUT - from the log - most of the agents encountered issues and then exited. 
[Here's the full log](https://github.com/oceanprotocol/pdr-backend/files/12999050/log.txt). You'll see errors in the last portion of the log.

An example symptom: aquarius complains that it can't see "development" network:
```text
Traceback (most recent call last):
  File "events-monitor-main.py", line 51, in <module>
    run_events_monitor()
  File "events-monitor-main.py", line 37, in run_events_monitor
    monitor = EventsMonitor(setup_web3(logger))
  File "/aquarius/aquarius/events/events_monitor.py", line 84, in __init__
    self._start_block = get_metadata_start_block()
  File "/aquarius/aquarius/events/util.py", line 244, in get_metadata_start_block
    if "startBlock" in address_json[network]
KeyError: 'development'
```

**Comment by trentmc** [comment]
My workaround was to run Barge in an Azure VPS. See [pdr-backend#297](https://github.com/oceanprotocol/pdr-backend/issues/297) where I created a [README](https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/vps.md) to run barge from a VPS. 

This README is currently in pdr-backend; we could port its instructions elsewhere too. But I don't see that as a priority, therefore I won't bother creating issues in this repo, or ocean.py etc.

**Comment by trentmc** [comment]
Here's the log from my Azure VM:
[out.txt](https://github.com/oceanprotocol/barge/files/13319150/out.txt)
